name: Run Selenium test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
             java-version: "23"
             cache: maven
             distribution: "temurin"
        - uses: browser-actions/setup-chrome@latest
        - run: mvn clean test
